# -*- coding: utf-8 -*-
"""Project Euler_Multiples of 3 or 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iedXZZzlylJaFu8qRfCah3U3tUinUhzB

**Problem 1**

<p>If we list all the natural numbers below $10$ that are multiples of $3$ or $5$, we get $3, 5, 6$ and $9$. The sum of these multiples is $23$.</p>
<p>Find the sum of all the multiples of $3$ or $5$ below $1000$.</p>
"""

#Multiples generator

def multiples_generator(num, end_num):
  m = []
  a = 0
  while True:
    a += 1
    multiples = num * a
    m.append(multiples)
    if m[-1] >= end_num:
      break
  return(m)

#Generate all the multiples of 3 and 5 that below 1000
multiples_3 = multiples_generator(3,1000)
multiples_5 = multiples_generator(5,1000)

if multiples_3[-1] >= 1000:
  multiples_3.pop(-1)

if multiples_5[-1] >= 1000:
  multiples_5.pop(-1)

#Remove the common multiple of 3 and 5 and store them in a new list
all_m = multiples_3 + multiples_5
d_m = list(set(all_m))

#Aggregate all the number in the list
print(sum(d_m))